import { create } from 'zustand';

type Language = 'en' | 'so';

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    stations: 'Stations',
    slots: 'Slot Management',
    revenue: 'Revenue Analytics',
    users: 'User Management',
    blacklist: 'Blacklist',
    notifications: 'Notifications',
    settings: 'Settings',
    login: 'Login',
    logout: 'Logout',
    search: 'Search...',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    close: 'Close',
    confirm: 'Confirm',
    username: 'Username',
    password: 'Password',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    welcome: 'Welcome',
    totalRevenue: 'Total Revenue',
    totalCustomers: 'Total Customers',
    dailyRevenue: 'Daily Revenue',
    monthlyRevenue: 'Monthly Revenue',
    dailyCustomers: 'Daily Customers',
    monthlyCustomers: 'Monthly Customers',
    recentTransactions: 'Recent Transactions',
    transactions: 'Transactions',
    viewAll: 'View All',
    showMore: 'Show More',
    showLess: 'Show Less',
    noData: 'No data available',
    stationName: 'Station Name',
    location: 'Location',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    online: 'Online',
    offline: 'Offline',
    addStation: 'Add Station',
    editStation: 'Edit Station',
    deleteStation: 'Delete Station',
    stationDetails: 'Station Details',
    slotManagement: 'Slot Management',
    available: 'Available',
    rented: 'Rented',
    overdue: 'Overdue',
    powerBanks: 'Power Banks',
    rentals: 'Active Rentals',
    stationComparison: 'Station Comparison',
    profileAndSettings: 'Profile & Settings',
    manageProfileAndSettings: 'Manage your profile and system preferences',
    systemPreferences: 'System Preferences',
    securitySettings: 'Security Settings',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    enterCurrentPassword: 'Enter current password',
    enterNewPassword: 'Enter new password',
    confirmNewPasswordPlaceholder: 'Confirm new password',
    updatePassword: 'Update Password',
    passwordsDoNotMatch: 'Passwords do not match',
    passwordUpdatedSuccess: 'Password updated successfully',
    failedToUpdatePassword: 'Failed to update password',
    accountActions: 'Account Actions',
    deleteAccount: 'Delete Account',
    deleteAccountConfirm: 'Are you sure you want to delete your account? This action cannot be undone.',
    administrator: 'Administrator',
    regularUser: 'Regular User',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    timezone: 'Timezone',
    utc: 'UTC (Coordinated Universal Time)',
    eat: 'EAT (East Africa Time)',
    gmt: 'GMT (Greenwich Mean Time)',
    dateFormat: 'Date Format',
    mmddyyyy: 'MM/DD/YYYY',
    ddmmyyyy: 'DD/MM/YYYY',
    yyyymmdd: 'YYYY-MM-DD',
    timeFormat: 'Time Format',
    hour12: '12-hour',
    hour24: '24-hour',
    autoLogout: 'Auto Logout (minutes)',
  },
  so: {
    dashboard: 'Bogga Hore',
    stations: 'Xarumaha',
    slots: 'Maaraynta Meelaha',
    revenue: 'Falanqaynta Dakhliga',
    users: 'Maaraynta Isticmaalayaasha',
    blacklist: 'Liiska Madow',
    notifications: 'Ogeysiisyada',
    settings: 'Hagaajinta',
    login: 'Soo Gal',
    logout: 'Ka Bax',
    search: 'Raadi...',
    loading: 'Soo dejinaya...',
    error: 'Khalad',
    success: 'Guul',
    cancel: 'Ka noqo',
    save: 'Kaydi',
    delete: 'Tirtir',
    edit: 'Wax ka beddel',
    add: 'Kudar',
    close: 'Xir',
    confirm: 'Xaqiiji',
    username: 'Magaca isticmaalaha',
    password: 'Furaha sirta',
    signIn: 'Soo Gal',
    signOut: 'Ka Bax',
    welcome: 'Soo dhawoow',
    totalRevenue: 'Wadarta Dakhliga',
    totalCustomers: 'Wadarta Macaamiisha',
    dailyRevenue: 'Dakhliga Maalinlaha',
    monthlyRevenue: 'Dakhliga Bishiiba',
    dailyCustomers: 'Macaamiisha Maalinlaha',
    monthlyCustomers: 'Macaamiisha Bishiiba',
    recentTransactions: 'Macaamiilada Dhawaan',
    transactions: 'Macaamilaadka',
    viewAll: 'Arag Dhammaan',
    showMore: 'Tus Wax Badan',
    showLess: 'Tus Wax Yar',
    noData: 'Xog ma jirto',
    stationName: 'Magaca Xarunta',
    location: 'Goobta',
    status: 'Xaalada',
    active: 'Firfircoon',
    inactive: 'Aan firfircoonayn',
    online: 'Ku xiran',
    offline: 'Ka baxsan',
    addStation: 'Kudar Xarun',
    editStation: 'Wax ka beddel Xarunta',
    deleteStation: 'Tirtir Xarunta',
    stationDetails: 'Faahfaahinta Xarunta',
    slotManagement: 'Maaraynta Meelaha',
    available: 'Diyaar',
    rented: 'La kireystay',
    overdue: 'Waqtigu ka dhamaadey',
    powerBanks: 'Banka Tamarta',
    rentals: 'Kireeysiga Firfircoon',
    stationComparison: 'Barbar dhigga Xarumaha',
    profileAndSettings: 'Xogta & Hagaajinta',
    manageProfileAndSettings: 'Maamul xogtaada iyo hagaajinta nidaamka',
    systemPreferences: 'Doorashooyinka Nidaamka',
    securitySettings: 'Hagaajinta Amniga',
    currentPassword: 'Furaha Hadda',
    newPassword: 'Furaha Cusub',
    confirmNewPassword: 'Xaqiiji Furaha Cusub',
    enterCurrentPassword: 'Geli furaha hadda',
    enterNewPassword: 'Geli furaha cusub',
    confirmNewPasswordPlaceholder: 'Xaqiiji furaha cusub',
    updatePassword: 'Cusboonaysii Furaha',
    passwordsDoNotMatch: 'Furayaashu ma iswaafaqaan',
    passwordUpdatedSuccess: 'Furaha waa la cusboonaysiiyay',
    failedToUpdatePassword: 'Waa lagu guuldareystay cusboonaysiinta furaha',
    accountActions: 'Ficilada Akoonka',
    deleteAccount: 'Tirtir Akoonka',
    deleteAccountConfirm: 'Ma hubtaa inaad rabto inaad tirtirto akoonkaaga? Ficilkan dib looma celin karo.',
    administrator: 'Maamulaha',
    regularUser: 'Isticmaale Caadi ah',
    language: 'Luuqada',
    theme: 'Muuqaalka',
    light: 'Iftiinka',
    dark: 'Mugdiga',
    timezone: 'Waqtiga Aagga',
    utc: 'UTC (Waqtiga Isku-dubbaridka Caalamiga)',
    eat: 'EAT (Waqtiga Bariga Afrika)',
    gmt: 'GMT (Waqtiga Greenwich)',
    dateFormat: 'Qaabka Taariikhda',
    mmddyyyy: 'BB/MM/SSSS',
    ddmmyyyy: 'MM/BB/SSSS',
    yyyymmdd: 'SSSS-BB-MM',
    timeFormat: 'Qaabka Waqtiga',
    hour12: '12-saac',
    hour24: '24-saac',
    autoLogout: 'Is ka saar Tooska (daqiiqado)',
  },
};

interface LanguageState {
  language: Language;
  t: (key: string) => string;
  changeLanguage: (lang: Language) => void;
  initLanguage: () => void;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: 'en',

  t: (key: string) => {
    const lang = get().language;
    return translations[lang]?.[key] || translations.en[key] || key;
  },

  changeLanguage: (lang: Language) => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('systemLanguage', lang);
      window.dispatchEvent(new CustomEvent('languageChange', { detail: lang }));
    }
    set({ language: lang });
  },

  initLanguage: () => {
    if (typeof window === 'undefined') return;
    const stored = localStorage.getItem('systemLanguage') as Language | null;
    if (stored && (stored === 'en' || stored === 'so')) {
      set({ language: stored });
    }
  },
}));
